valid_size: 16
train_clip_second: 0.5
sample_rate: 22050
fft_window_shift: 256
fft_window_size: 1024
fft_size: 2048
mel_bands: 80

seed: 1
batch_size: 8
test_every: 2000
save_every: 10000
max_iterations: 2000000

layers: 30
kernel_width: 2
dilation_block: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
residual_channels: 128
skip_channels: 128
loss_type: mix-gaussian-pdf
num_mixtures: 1
log_scale_min: -9.0

conditioner: 
  filter_sizes: [[32, 3], [32, 3]]
  upsample_factors: [16, 16]

learning_rate: 0.001
gradient_max_norm: 100.0
anneal: 
  every: 200000
  rate: 0.5
